import type { NextPage } from 'next';
import Head from 'next/head';
import Landing from '../components/Landing';

const Home: NextPage = () => {
  return (
    <div className="body w-full h-full bg-slate-100">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Landing />
      </main>
    </div>
  );
};

export default Home;
