import type { NextPage } from 'next';
import Head from 'next/head';
import CardGeneratorPage from '../components/CardGeneratorPage';
import Faq from '../components/Faq';
import Footer from '../components/Footer';
import InfoGroup from '../components/InfoGroup';
import InfoGroup2 from '../components/InfoGroup2';
import LandingBottom from '../components/LandingBottom';
import LandingTop from '../components/LandingTop';
import Navbar from '../components/Navbar';

const Home: NextPage = () => {
  return (
    <div className="body w-full h-full  mx-auto">
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <div className="bgliustkisim  mx-auto bg-gradient-to-t from-[#E3F2F7] to-white h-[910px]">
            <div className="bgliustkisimicerik w-full max-w-screen-xl mt-4 bg-transparent mx-auto h-[910px]">
              <Navbar />
              <LandingTop />
            </div>
          </div>
          <div className=" bg-[#666666] h-[630px] mx-auto">
            <div className=" w-full secondArea h-[630px] max-w-screen-xl mx-auto">
              <LandingBottom />
            </div>
          </div>
          <div className="mx-auto max-w-screen-xl">
            <CardGeneratorPage />
            <InfoGroup />
            <Faq />
            <InfoGroup2 />
            <Footer />
          </div>
        </main>
      </div>
    </div>
  );
};

export default Home;
